@extends('layouts.admin')

@section('title', 'Detail Stok Room')
@section('eyebrow', 'Persediaan')
@section('page-title', 'Detail Stok')

@section('content')
    <section class="dashboard-heading category-form-heading"><div><p class="dashboard-heading__eyebrow">{{ $stock->warehouse?->code }} · {{ $stock->warehouse?->name }}</p><h2>{{ $stock->productVariant?->sku }}</h2><p>{{ $stock->productVariant?->product?->name }} · {{ $stock->productVariant?->color?->name }} / {{ $stock->productVariant?->size?->name }}</p></div><div class="dashboard-heading__actions"><a href="{{ route('admin.warehouse-stocks.index',['warehouse'=>$stock->warehouse_id]) }}" class="button button--secondary">Kembali</a><a href="{{ route('admin.stock-movements.index',['warehouse'=>$stock->warehouse_id,'search'=>$stock->productVariant?->sku]) }}" class="button button--secondary">Riwayat Mutasi</a><a href="{{ route('admin.stock-adjustments.create',['stock'=>$stock->id]) }}" class="button button--secondary">Stock Opname</a><a href="{{ route('admin.stock-movements.create',['stock'=>$stock->id]) }}" class="button button--primary">Catat Mutasi</a></div></section>

    @if(session('success'))<div class="user-alert user-alert--success" role="status"><span class="user-alert__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg></span><span>{{ session('success') }}</span></div>@endif
    @if(session('error'))<div class="user-alert user-alert--danger" role="alert"><span class="user-alert__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 8v4m0 4h.01"/><circle cx="12" cy="12" r="9"/></svg></span><span>{{ session('error') }}</span></div>@endif

    <section class="stock-detail-summary">
        <article class="stock-quantity-card glass-panel"><small>Stok Fisik</small><strong>{{ number_format($stock->quantity_on_hand) }}</strong><span>On hand</span></article>
        <article class="stock-quantity-card glass-panel"><small>Reservasi</small><strong>{{ number_format($stock->quantity_reserved) }}</strong><span>Dialokasikan untuk pesanan</span></article>
        <article class="stock-quantity-card glass-panel"><small>Rusak</small><strong>{{ number_format($stock->quantity_damaged) }}</strong><span>Tidak layak jual</span></article>
        <article class="stock-quantity-card stock-quantity-card--available glass-panel"><small>Stok Tersedia</small><strong>{{ number_format($stock->availableQuantity()) }}</strong><span>Fisik − reservasi − rusak</span></article>
        <article class="stock-quantity-card glass-panel"><small>Stok Minimum</small><strong>{{ number_format($stock->minimum_stock) }}</strong><span>Batas peringatan</span></article>
        <article class="stock-quantity-card glass-panel"><small>Status</small><strong class="stock-status stock-status--{{ $stock->stockStatus() }}">{{ $stock->stockStatusLabel() }}</strong><span>{{ $stock->needsRestock() ? 'Perlu perhatian/restock' : 'Persediaan masih aman' }}</span></article>
    </section>

    <div class="category-form-layout">
        <div class="category-form-main">
            <section class="category-form-card glass-panel"><div class="category-form-card__header"><span class="category-form-card__icon category-form-card__icon--peach"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="m4 7 8 4 8-4v10l-8 4-8-4V7Z"/></svg></span><div><p class="dashboard-heading__eyebrow">Identitas SKU</p><h3>{{ $stock->productVariant?->product?->name }}</h3><p>Variasi dan produk yang tercatat pada titik stok ini.</p></div></div><dl class="category-meta-card stock-detail-list"><div><dt>SKU</dt><dd>{{ $stock->productVariant?->sku }}</dd></div><div><dt>Kode Produk</dt><dd>{{ $stock->productVariant?->product?->code }}</dd></div><div><dt>Kategori</dt><dd>{{ $stock->productVariant?->product?->category?->name ?? '-' }}</dd></div><div><dt>Warna</dt><dd>{{ $stock->productVariant?->color?->name ?? '-' }}</dd></div><div><dt>Ukuran</dt><dd>{{ $stock->productVariant?->size?->name ?? '-' }}</dd></div><div><dt>Status Variasi</dt><dd>{{ $stock->productVariant?->is_active ? 'Aktif' : 'Nonaktif' }}</dd></div></dl></section>
            <section class="category-form-card glass-panel"><div class="category-form-card__header"><span class="category-form-card__icon category-form-card__icon--green"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m3 9 9-6 9 6v11H3V9Z"/><path d="M8 20v-7h8v7"/></svg></span><div><p class="dashboard-heading__eyebrow">Lokasi</p><h3>{{ $stock->warehouse?->name }}</h3><p>{{ $stock->warehouse?->address ?: 'Alamat room belum diisi.' }}</p></div></div><div class="category-examples"><span>{{ $stock->warehouse?->code }}</span><span>{{ $stock->warehouse?->is_active ? 'Room aktif' : 'Room nonaktif' }}</span><a href="{{ route('admin.warehouses.show',$stock->warehouse_id) }}">Detail room</a></div></section>
        </div>
        <aside class="category-form-side"><section class="category-meta-card glass-panel"><p class="dashboard-heading__eyebrow">Metadata</p><h3>Riwayat konfigurasi</h3><dl><div><dt>Dibuat</dt><dd>{{ $stock->created_at?->format('d M Y, H:i') }}</dd></div><div><dt>Oleh</dt><dd>{{ $stock->createdBy?->name ?? 'Sistem' }}</dd></div><div><dt>Diperbarui</dt><dd>{{ $stock->updated_at?->format('d M Y, H:i') }}</dd></div><div><dt>Oleh</dt><dd>{{ $stock->updatedBy?->name ?? 'Sistem' }}</dd></div></dl></section><section class="category-form-note glass-panel"><span class="category-form-note__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6l8-3Z"/></svg></span><div><strong>Stok dijaga melalui transaksi</strong><p>Jumlah fisik tidak diedit di halaman ini. Gunakan Mutasi Stok untuk transaksi masuk/keluar atau Penyesuaian Stok untuk koreksi hasil stock opname agar setiap perubahan saldo selalu menghasilkan ledger. Reservasi dan barang rusak tetap dilindungi sebagai kuantitas non-available.</p></div></section>@if($stock->quantity_on_hand===0 && $stock->quantity_reserved===0 && $stock->quantity_damaged===0)<form action="{{ route('admin.warehouse-stocks.destroy',$stock) }}" method="POST" class="category-form-actions glass-panel" data-confirm-form data-confirm-message="Hapus pendaftaran SKU {{ $stock->productVariant?->sku }} dari room ini?">@csrf @method('DELETE')<button type="submit" class="button button--ghost">Hapus Pendaftaran</button></form>@endif</aside>
    </div>
@endsection
