@extends('layouts.admin')
@section('title','Pengiriman')
@section('eyebrow','Penjualan')
@section('page-title','Pengiriman')
@section('content')
<section class="dashboard-heading compact-page-heading"><div><p class="dashboard-heading__eyebrow">Pelacakan Pesanan</p><h2>Status pengiriman</h2><p>Gunakan tiga status utama sesuai kebutuhan: Dikemas, Sedang dalam perjalanan, dan Diterima.</p></div></section>
<form method="GET" action="{{ route('admin.shipments.index') }}" class="compact-filter-bar glass-panel" data-ajax-filter><input type="search" name="search" value="{{ $search }}" placeholder="Transaksi, pelanggan, kurir, resi"><select name="status"><option value="">Semua status</option><option value="pending" @selected($status==='pending')>Belum Dikemas</option><option value="packed" @selected($status==='packed')>Dikemas</option><option value="in_transit" @selected($status==='in_transit')>Dalam Perjalanan</option><option value="delivered" @selected($status==='delivered')>Diterima</option></select><button class="button button--secondary">Terapkan</button></form>
<section class="glass-panel compact-table-card"><div class="table-scroll"><table class="compact-table"><thead><tr><th>Transaksi</th><th>Pelanggan</th><th>Kurir</th><th>Resi</th><th>Status</th><th>Diperbarui</th><th></th></tr></thead><tbody>@forelse($shipments as $s)<tr><td><strong>{{ $s->order?->transaction_number }}</strong></td><td>{{ $s->order?->customer_name }}</td><td>{{ $s->courier ?: '-' }}</td><td>{{ $s->tracking_number ?: '-' }}</td><td><span class="status-pill {{ $s->status==='delivered'?'status-pill--success':($s->status==='in_transit'?'status-pill--info':'status-pill--warning') }}">{{ $s->statusLabel() }}</span></td><td>{{ $s->updated_at?->format('d M Y H:i') }}</td><td><a href="{{ route('admin.shipments.edit',$s) }}" class="button button--small button--primary" data-modal-form data-modal-title="Perbarui Pengiriman">Update</a></td></tr>@empty<tr><td colspan="7"><div class="empty-state">Belum ada data pengiriman.</div></td></tr>@endforelse</tbody></table></div><div class="compact-pagination">{{ $shipments->links() }}</div></section>
@endsection
