@php
    $selectedProduct = old('product_id', $productVariant->product_id);
    $selectedColor = old('color_id', $productVariant->color_id);
    $selectedSize = old('size_id', $productVariant->size_id);
@endphp

<div class="category-form-main">
    <section class="category-form-card glass-panel">
        <div class="category-form-card__header"><span class="category-form-card__icon category-form-card__icon--peach"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m8 4 4 2 4-2 4 2v5l-4 2-4-2-4 2-4-2V6l4-2Z"/><path d="M12 6v5"/></svg></span><div><p class="dashboard-heading__eyebrow">Kombinasi</p><h3>Produk, warna, dan ukuran</h3><p>Satu kombinasi hanya dapat dibuat satu kali. Untuk produk tanpa ukuran khusus, gunakan master ukuran seperti ALL SIZE.</p></div></div>
        <div class="category-form-grid">
            <label class="category-form-field category-form-field--full"><span>Produk <em>*</em></span><select name="product_id" required data-variant-product>@foreach($products as $product)<option value="{{ $product->id }}" data-code="{{ $product->code }}" data-price="{{ (float)$product->selling_price }}" data-weight="{{ $product->weight_grams }}" @selected((string)$selectedProduct===(string)$product->id)>{{ $product->code }} · {{ $product->name }}</option>@endforeach</select><small>Harga jual dasar mengikuti produk yang dipilih.</small>@error('product_id')<span class="category-field-error">{{ $message }}</span>@enderror</label>
            <label class="category-form-field"><span>Warna <em>*</em></span><select name="color_id" required data-variant-color><option value="">Pilih warna</option>@foreach($colors as $color)<option value="{{ $color->id }}" data-code="{{ $color->code }}" @selected((string)$selectedColor===(string)$color->id)>{{ $color->code }} · {{ $color->name }}{{ isset($color->is_active) && !$color->is_active ? ' · Nonaktif' : '' }}</option>@endforeach</select>@error('color_id')<span class="category-field-error">{{ $message }}</span>@enderror</label>
            <label class="category-form-field"><span>Ukuran <em>*</em></span><select name="size_id" required data-variant-size><option value="">Pilih ukuran</option>@foreach($sizes as $size)<option value="{{ $size->id }}" data-code="{{ $size->code }}" @selected((string)$selectedSize===(string)$size->id)>{{ $size->code }} · {{ $size->name }}{{ isset($size->is_active) && !$size->is_active ? ' · Nonaktif' : '' }}</option>@endforeach</select>@error('size_id')<span class="category-field-error">{{ $message }}</span>@enderror</label>
            <label class="category-form-field category-form-field--full"><span>SKU {{ $isEditing ? '*' : '' }}</span><input type="text" name="sku" value="{{ old('sku',$productVariant->sku) }}" maxlength="100" placeholder="Otomatis: HD-0001-PCH-M" autocomplete="off" {{ $isEditing ? 'required' : '' }} data-variant-sku><small>{{ $isEditing ? 'SKU tersimpan dapat disesuaikan manual.' : 'Kosongkan agar sistem membuat SKU otomatis dari kode produk, warna, dan ukuran.' }}</small>@error('sku')<span class="category-field-error">{{ $message }}</span>@enderror</label>
        </div>
    </section>

    <section class="category-form-card glass-panel">
        <div class="category-form-card__header"><span class="category-form-card__icon category-form-card__icon--green"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M8 12h8M12 8v8"/></svg></span><div><p class="dashboard-heading__eyebrow">Penyesuaian</p><h3>Harga dan berat khusus</h3><p>Biarkan berat kosong untuk mengikuti berat dasar produk. Tambahan harga 0 berarti variasi menggunakan harga jual dasar.</p></div></div>
        <div class="category-form-grid">
            <label class="category-form-field"><span>Tambahan Harga <em>*</em></span><input type="number" name="additional_price" value="{{ old('additional_price',$productVariant->additional_price ?? 0) }}" min="0" step="1" required data-variant-additional-price><small>Masukkan 0 jika tidak ada tambahan.</small>@error('additional_price')<span class="category-field-error">{{ $message }}</span>@enderror</label>
            <label class="category-form-field"><span>Berat Khusus (gram)</span><input type="number" name="weight_grams" value="{{ old('weight_grams',$productVariant->weight_grams) }}" min="1" step="1" placeholder="Kosong = ikut produk" data-variant-weight><small>Gunakan hanya jika berat variasi berbeda dari produk dasar.</small>@error('weight_grams')<span class="category-field-error">{{ $message }}</span>@enderror</label>
        </div>
    </section>

    <section class="category-form-card glass-panel">
        <div class="category-form-card__header"><span class="category-form-card__icon category-form-card__icon--peach"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></svg></span><div><p class="dashboard-heading__eyebrow">Ketersediaan</p><h3>Status variasi</h3><p>Variasi nonaktif tetap tersimpan untuk menjaga histori dan tidak digunakan pada transaksi baru.</p></div></div>
        <div class="category-status-options"><label class="category-status-option"><input type="radio" name="is_active" value="1" @checked((string)old('is_active',$productVariant->is_active ? '1':'0')==='1')><span class="category-status-option__surface"><span class="category-status-option__icon category-status-option__icon--green"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 6 9 17l-5-5"/></svg></span><span><strong>Aktif</strong><small>Dapat digunakan pada stok dan transaksi.</small></span></span></label><label class="category-status-option"><input type="radio" name="is_active" value="0" @checked((string)old('is_active',$productVariant->is_active ? '1':'0')==='0')><span class="category-status-option__surface"><span class="category-status-option__icon category-status-option__icon--peach"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M8 12h8"/></svg></span><span><strong>Nonaktif</strong><small>Tidak dipakai pada transaksi baru.</small></span></span></label></div>
        @error('is_active')<span class="category-field-error">{{ $message }}</span>@enderror
    </section>
</div>

<aside class="category-form-side">
    <section class="variant-preview-card glass-panel"><p class="dashboard-heading__eyebrow">Preview Variasi</p><h3>Identitas SKU</h3><div class="variant-preview-sku" data-variant-sku-preview>{{ old('sku',$productVariant->sku) ?: 'SKU otomatis' }}</div><dl><div><dt>Harga Akhir</dt><dd data-variant-final-price>Rp0</dd></div><div><dt>Berat Efektif</dt><dd data-variant-effective-weight>-</dd></div></dl><p>Preview mengikuti pilihan pada form dan tidak mengubah data sampai formulir disimpan.</p></section>
    @if($isEditing)<section class="category-meta-card glass-panel"><p class="dashboard-heading__eyebrow">Metadata</p><h3>Riwayat data</h3><dl><div><dt>Dibuat</dt><dd>{{ $productVariant->created_at?->format('d M Y, H:i') ?? '-' }}</dd></div><div><dt>Diperbarui</dt><dd>{{ $productVariant->updated_at?->format('d M Y, H:i') ?? '-' }}</dd></div></dl></section>@endif
    <section class="category-form-note glass-panel"><span class="category-form-note__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></svg></span><div><strong>Stok belum diinput di sini</strong><p>Jumlah stok akan disimpan per variasi dan per room agar perpindahan serta riwayat stok dapat diaudit.</p></div></section>
    <div class="category-form-actions glass-panel"><a href="{{ route('admin.product-variants.index', $productVariant->product_id ? ['product'=>$productVariant->product_id] : []) }}" class="button button--secondary">Batal</a><button type="submit" class="button button--primary"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 12.5 9 16l10-10"/></svg>{{ $submitLabel }}</button></div>
</aside>
