@extends('layouts.admin')
@section('title','Transaksi Baru')
@section('eyebrow','Penjualan')
@section('page-title','Transaksi Baru')
@section('content')
<section class="dashboard-heading category-form-heading"><div><p class="dashboard-heading__eyebrow">Penjualan Baru</p><h2>Transaksi online atau offline</h2><p>Pilih room, pelanggan, metode pembayaran, lalu tambahkan produk. Harga dihitung dari database dan tidak dapat dimanipulasi dari form.</p></div></section>
@if($errors->any())<div class="user-alert user-alert--danger">Periksa kembali data transaksi. {{ $errors->first() }}</div>@endif
<form action="{{ route('admin.sales.store') }}" method="POST" enctype="multipart/form-data" class="modal-friendly-form" data-sales-form>@csrf
<div class="category-form-card glass-panel"><div class="category-form-grid"><label class="category-form-field"><span>Kanal <em>*</em></span><select name="channel" required data-sale-channel><option value="offline">Offline / toko</option><option value="online">Online</option></select></label><label class="category-form-field"><span>Room <em>*</em></span><select name="warehouse_id" required data-sale-warehouse><option value="">Pilih room</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->code }} · {{ $w->name }}</option>@endforeach</select></label><label class="category-form-field"><span>Nama Pelanggan <em>*</em></span><input name="customer_name" value="{{ old('customer_name','Pelanggan Umum') }}" required></label><label class="category-form-field"><span>Nomor Telepon</span><input name="customer_phone" value="{{ old('customer_phone') }}" placeholder="08xxxxxxxxxx"></label><label class="category-form-field category-form-field--full"><span>Alamat Pengiriman</span><textarea name="shipping_address" rows="2" placeholder="Wajib untuk transaksi online">{{ old('shipping_address') }}</textarea></label><label class="category-form-field"><span>Metode Pembayaran <em>*</em></span><select name="payment_method" required data-sale-payment><option value="cash">Tunai</option><option value="bank_transfer">Transfer Bank</option><option value="qris">QRIS</option></select></label><label class="category-form-field"><span>Ongkos Kirim</span><input type="number" min="0" name="shipping_cost" value="{{ old('shipping_cost',0) }}"></label><label class="category-form-field"><span>Tanggal <em>*</em></span><input type="datetime-local" name="transaction_date" value="{{ old('transaction_date',now()->format('Y-m-d\TH:i')) }}" required></label><label class="category-form-field"><span>Bukti Pembayaran</span><input type="file" name="payment_proof" accept="image/jpeg,image/png,image/webp,application/pdf"><small>Untuk QRIS/transfer. Maks. 5 MB.</small></label><label class="category-form-field category-form-field--full"><span>Catatan</span><textarea name="notes" rows="2">{{ old('notes') }}</textarea></label></div></div>
<div class="category-form-card glass-panel"><div class="compact-master-panel__header"><div><p class="dashboard-heading__eyebrow">Produk</p><h3>Item transaksi</h3></div><button type="button" class="button button--secondary button--small" data-sale-add-item>+ Produk</button></div><div data-sale-items></div><template data-sale-item-template><div class="sale-item-row"><select name="items[__INDEX__][product_variant_id]" required data-sale-variant><option value="">Pilih SKU</option>@foreach($stocks as $s)<option value="{{ $s->product_variant_id }}" data-warehouse="{{ $s->warehouse_id }}" data-price="{{ $s->productVariant?->finalSellingPrice() }}" data-available="{{ $s->availableQuantity() }}">{{ $s->productVariant?->sku }} · {{ $s->productVariant?->product?->name }} · {{ $s->productVariant?->color?->name }}/{{ $s->productVariant?->size?->name }} · stok {{ $s->availableQuantity() }}</option>@endforeach</select><input type="number" name="items[__INDEX__][quantity]" min="1" value="1" required data-sale-qty><span class="sale-item-row__price" data-sale-line-price>Rp0</span><button type="button" class="icon-button" data-sale-remove-item>×</button></div></template><div class="sale-form-total"><span>Estimasi sebelum diskon</span><strong data-sale-estimate>Rp0</strong><small>Diskon aktif dihitung ulang oleh server saat transaksi disimpan.</small></div></div>
<div class="modal-form-actions"><button type="button" class="button button--secondary" data-data-modal-close>Batal</button><button type="submit" class="button button--primary">Simpan Transaksi</button></div></form>
@endsection
