@extends('layouts.admin')
@section('title','Penjualan')
@section('eyebrow','Penjualan')
@section('page-title','Transaksi Penjualan')
@section('content')
<section class="dashboard-heading compact-page-heading"><div><p class="dashboard-heading__eyebrow">Online & Offline</p><h2>Transaksi penjualan</h2><p>Kelola transaksi toko dan pesanan online dari satu halaman. Stok langsung terhubung ke room.</p></div><a href="{{ route('admin.sales.create') }}" class="button button--primary" data-modal-form data-modal-title="Transaksi Penjualan Baru">+ Transaksi</a></section>
<div class="compact-stat-grid"><article class="compact-stat-card"><small>Transaksi Hari Ini</small><strong>{{ number_format($stats['today']) }}</strong></article><article class="compact-stat-card"><small>Online</small><strong>{{ number_format($stats['online']) }}</strong></article><article class="compact-stat-card"><small>Offline</small><strong>{{ number_format($stats['offline']) }}</strong></article><article class="compact-stat-card compact-stat-card--green"><small>Pendapatan Lunas Hari Ini</small><strong>Rp{{ number_format($stats['revenue'],0,',','.') }}</strong></article></div>
<form method="GET" action="{{ route('admin.sales.index') }}" class="compact-filter-bar glass-panel" data-ajax-filter><input type="search" name="search" value="{{ $filters['search'] }}" placeholder="Nomor transaksi / pelanggan"><select name="channel"><option value="">Semua kanal</option><option value="online" @selected($filters['channel']==='online')>Online</option><option value="offline" @selected($filters['channel']==='offline')>Offline</option></select><select name="payment"><option value="">Semua pembayaran</option><option value="waiting_verification" @selected($filters['payment']==='waiting_verification')>Menunggu Verifikasi</option><option value="paid" @selected($filters['payment']==='paid')>Lunas</option><option value="rejected" @selected($filters['payment']==='rejected')>Ditolak</option></select><select name="status"><option value="">Semua status</option><option value="waiting_payment" @selected($filters['status']==='waiting_payment')>Menunggu Bayar</option><option value="processing" @selected($filters['status']==='processing')>Diproses</option><option value="completed" @selected($filters['status']==='completed')>Selesai</option><option value="cancelled" @selected($filters['status']==='cancelled')>Dibatalkan</option></select><button class="button button--secondary">Terapkan</button></form>
<section class="glass-panel compact-table-card"><div class="table-scroll"><table class="compact-table"><thead><tr><th>Transaksi</th><th>Pelanggan</th><th>Kanal</th><th>Total</th><th>Pembayaran</th><th>Pesanan</th><th>Waktu</th><th></th></tr></thead><tbody>@forelse($orders as $o)<tr><td><strong>{{ $o->transaction_number }}</strong><small>{{ $o->warehouse?->name }} · {{ $o->items_count }} item</small></td><td><strong>{{ $o->customer_name }}</strong><small>{{ $o->customer_phone ?: '-' }}</small></td><td><span class="status-pill {{ $o->channel==='online'?'status-pill--info':'status-pill--neutral' }}">{{ $o->channelLabel() }}</span></td><td><strong>Rp{{ number_format((float)$o->grand_total,0,',','.') }}</strong></td><td><span class="status-pill {{ $o->payment_status==='paid'?'status-pill--success':($o->payment_status==='rejected'?'status-pill--danger':'status-pill--warning') }}">{{ $o->paymentStatusLabel() }}</span></td><td>{{ $o->orderStatusLabel() }}</td><td>{{ $o->transaction_date?->format('d M Y H:i') }}</td><td><a class="table-action-link" href="{{ route('admin.sales.show',$o) }}">Detail</a></td></tr>@empty<tr><td colspan="8"><div class="empty-state">Belum ada transaksi penjualan.</div></td></tr>@endforelse</tbody></table></div><div class="compact-pagination">{{ $orders->links() }}</div></section>
@endsection
