@extends('layouts.admin')
@section('title','Pembayaran')
@section('eyebrow','Penjualan')
@section('page-title','Pembayaran')
@section('content')
<section class="dashboard-heading compact-page-heading"><div><p class="dashboard-heading__eyebrow">Verifikasi Pembayaran</p><h2>QRIS, transfer, dan tunai</h2><p>Bukti pembayaran hanya dapat dibuka oleh pengguna internal yang sedang login.</p></div></section>
<form method="GET" action="{{ route('admin.payments.index') }}" class="compact-filter-bar glass-panel" data-ajax-filter><input type="search" name="search" value="{{ $search }}" placeholder="Nomor pembayaran / transaksi / pelanggan"><select name="status"><option value="">Semua status</option><option value="pending" @selected($status==='pending')>Menunggu Verifikasi</option><option value="verified" @selected($status==='verified')>Lunas</option><option value="rejected" @selected($status==='rejected')>Ditolak</option></select><button class="button button--secondary">Terapkan</button></form>
<section class="glass-panel compact-table-card"><div class="table-scroll"><table class="compact-table"><thead><tr><th>Pembayaran</th><th>Transaksi</th><th>Metode</th><th>Nominal</th><th>Status</th><th>Bukti</th><th>Verifikator</th><th></th></tr></thead><tbody>@forelse($payments as $p)<tr><td><strong>{{ $p->payment_number }}</strong></td><td><strong>{{ $p->order?->transaction_number }}</strong><small>{{ $p->order?->customer_name }}</small></td><td>{{ $p->methodLabel() }}</td><td>Rp{{ number_format((float)$p->amount,0,',','.') }}</td><td><span class="status-pill {{ $p->status==='verified'?'status-pill--success':($p->status==='rejected'?'status-pill--danger':'status-pill--warning') }}">{{ $p->statusLabel() }}</span></td><td>@if($p->proof_path)<a class="table-action-link" href="{{ route('admin.payments.proof',$p) }}" target="_blank">Lihat Bukti</a>@else<span>-</span>@endif</td><td>{{ $p->verifiedBy?->name ?? '-' }}</td><td>@if($p->status==='pending')<a href="{{ route('admin.payments.edit',$p) }}" class="button button--small button--primary" data-modal-form data-modal-title="Verifikasi Pembayaran">Verifikasi</a>@endif</td></tr>@empty<tr><td colspan="8"><div class="empty-state">Belum ada pembayaran.</div></td></tr>@endforelse</tbody></table></div><div class="compact-pagination">{{ $payments->links() }}</div></section>
@endsection
