@extends('layouts.admin')
@section('title','Diskon & Promosi')
@section('eyebrow','Penjualan')
@section('page-title','Diskon & Promosi')
@section('content')
<section class="dashboard-heading compact-page-heading"><div><p class="dashboard-heading__eyebrow">Harga Promosi</p><h2>Diskon produk dan kategori</h2><p>Atur diskon persentase atau nominal tetap dengan periode aktif. Harga tidak pernah dibiarkan menjadi negatif.</p></div><a href="{{ route('admin.promotions.create') }}" class="button button--primary" data-modal-form data-modal-title="Tambah Promosi">+ Promosi</a></section>
<form method="GET" action="{{ route('admin.promotions.index') }}" class="compact-filter-bar glass-panel" data-ajax-filter><input type="search" name="search" value="{{ $search }}" placeholder="Nama promosi"><select name="status"><option value="">Semua status</option><option value="active" @selected($status==='active')>Aktif</option><option value="inactive" @selected($status==='inactive')>Nonaktif</option></select><button class="button button--secondary">Terapkan</button></form>
<section class="glass-panel compact-table-card"><div class="table-scroll"><table class="compact-table"><thead><tr><th>Promosi</th><th>Diskon</th><th>Target</th><th>Periode</th><th>Status</th><th></th></tr></thead><tbody>@forelse($promotions as $p)<tr><td><strong>{{ $p->name }}</strong></td><td>{{ $p->discountLabel() }}</td><td>@if($p->target_type==='all')Semua Produk@elseif($p->target_type==='product'){{ $p->product?->code }} · {{ $p->product?->name }}@else{{ $p->category?->code }} · {{ $p->category?->name }}@endif</td><td>{{ $p->starts_at?->format('d M Y') }} – {{ $p->ends_at?->format('d M Y') }}</td><td><span class="status-pill {{ $p->is_active?'status-pill--success':'status-pill--neutral' }}">{{ $p->is_active?'Aktif':'Nonaktif' }}</span></td><td><div class="table-action-group"><a href="{{ route('admin.promotions.edit',$p) }}" class="table-action-link" data-modal-form data-modal-title="Edit Promosi">Edit</a><form action="{{ route('admin.promotions.toggle',$p) }}" method="POST" data-ajax-action>@csrf @method('PATCH')<button class="table-action-link" type="submit">{{ $p->is_active?'Nonaktifkan':'Aktifkan' }}</button></form><form action="{{ route('admin.promotions.destroy',$p) }}" method="POST" data-ajax-action data-confirm-message="Arsipkan promosi {{ $p->name }}?">@csrf @method('DELETE')<button class="table-action-link table-action-link--danger" type="submit">Arsipkan</button></form></div></td></tr>@empty<tr><td colspan="6"><div class="empty-state">Belum ada promosi.</div></td></tr>@endforelse</tbody></table></div><div class="compact-pagination">{{ $promotions->links() }}</div></section>
@endsection
