@extends('layouts.admin')
@section('title','Transfer Room')
@section('eyebrow','Produk & Persediaan')
@section('page-title','Transfer Room')
@section('content')
<section class="dashboard-heading category-form-heading"><div><p class="dashboard-heading__eyebrow">Transfer Baru</p><h2>Pindahkan stok antar room</h2><p>Stok tersedia room asal akan berkurang dan stok fisik room tujuan bertambah dalam satu transaksi.</p></div></section>
@if($errors->any())<div class="user-alert user-alert--danger">Periksa kembali data transfer.</div>@endif
<form action="{{ route('admin.stock-transfers.store') }}" method="POST" class="modal-friendly-form" data-stock-transfer-form>@csrf
<div class="category-form-card glass-panel"><div class="category-form-grid"><label class="category-form-field"><span>Room Asal <em>*</em></span><select name="source_warehouse_id" required data-transfer-source><option value="">Pilih room</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->code }} · {{ $w->name }}</option>@endforeach</select></label><label class="category-form-field"><span>Room Tujuan <em>*</em></span><select name="destination_warehouse_id" required><option value="">Pilih room</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->code }} · {{ $w->name }}</option>@endforeach</select></label><label class="category-form-field"><span>Tanggal <em>*</em></span><input type="datetime-local" name="transfer_date" value="{{ old('transfer_date',now()->format('Y-m-d\TH:i')) }}" required></label><label class="category-form-field"><span>Catatan</span><input type="text" name="notes" value="{{ old('notes') }}" placeholder="Opsional"></label></div></div>
<div class="category-form-card glass-panel"><div class="compact-master-panel__header"><div><p class="dashboard-heading__eyebrow">Item Transfer</p><h3>Pilih SKU dan jumlah</h3></div><button type="button" class="button button--secondary button--small" data-transfer-add-item>+ Item</button></div><div data-transfer-items></div><template data-transfer-item-template><div class="transfer-item-row"><select name="items[__INDEX__][product_variant_id]" required data-transfer-variant><option value="">Pilih SKU</option>@foreach($stocks as $s)<option value="{{ $s->product_variant_id }}" data-warehouse="{{ $s->warehouse_id }}" data-available="{{ $s->availableQuantity() }}">{{ $s->productVariant?->sku }} · {{ $s->productVariant?->product?->name }} · tersedia {{ $s->availableQuantity() }}</option>@endforeach</select><input type="number" name="items[__INDEX__][quantity]" min="1" value="1" required><button type="button" class="icon-button" data-transfer-remove-item aria-label="Hapus item">×</button></div></template></div>
<div class="modal-form-actions"><button type="button" class="button button--secondary" data-data-modal-close>Batal</button><button type="submit" class="button button--primary">Proses Transfer</button></div></form>
@endsection
